name: sandbox-env
channels:
  - conda-forge
  - astra-toolbox/label/dev
  - ccpi
  
dependencies:
  - python=3.7
  - numpy=1.15
  - matplotlib
  - astra-toolbox=1.9.9
  - tomophantom
  - seaborn
  - ipywidgets
  - scipy
  - scikit-image
