name: sandbox-env
channels:
  - conda-forge
  - astra-toolbox/label/dev
  - ccpi
  
dependencies:
  - python==3.7
  - numpy==1.21.1
  - pip
  - matplotlib==3.4.3
  - astra==1.9.9.dev
  - copy
  - tomophantom==1.2
  - os
  - seaborn==0.11.0
  - ipywidgets==7.6.3
  - scipy==1.6.2
  - skimage==0.18.1
