name: sandbox-env
channels:
  - conda-forge
  - astra-toolbox/label/dev
  - ccpi
  
dependencies:
  - python=3.7
  - numpy=1.15
  - matplotlib=3.4.3
  - astra-toolbox=1.9.9
  - tomophantom
  - seaborn=0.11.0
  - ipywidgets=7.6.3
  - scipy=1.6.2
  - scikit-image
